# Embeddingレイヤを確認する
Embeddingレイヤは、単語IDを埋め込みベクトルに変換するためのレイヤである

In [5]:
import numpy as np

In [6]:
# 確認
a = b = np.ones((5,3))
a[...] = 3 #　numpyの配列の各要素に値を代入する
b = 3 # 変数に値を代入する
print("a=",a, "\n")
print("b=",b, "\n")

a= [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]] 

b= 3 



In [7]:
class Embedding:
    def __init__(self, W):
        """
        W : 重み行列, word2vecの埋め込み行列に相当する。配列形状は、(語彙数、埋め込みベクトルの要素数)
        """
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        """
        順伝播計算
        """
        W, = self.params # dWの後の,はリストから1つだけを抜き出すためにつけている
        self.idx = idx
        
        # 埋め込み行列から埋め込みベクトルを取り出す
        out = W[idx]
        
        return out

    def backward(self, dout):
        """
        逆伝播計算
        """
        dW, = self.grads # dWの後の,はリストから1つだけを抜き出すためにつけている
        
        # 配列の全ての要素に0を代入する
        dW[...] = 0 # [...]をつけると、全ての要素に代入してくれる
        
        # dWのidxの場所にdoutを代入する
        np.add.at(dW, self.idx, dout)
        return None

In [8]:
V = 10 # 語彙数
D = 3 # 埋め込みベクトルの要素数

# パラメータの初期化
embed_W = np.random.randn(V, D) 
print("embed_W=", embed_W)
print()

# オブジェクトの生成
emb = Embedding(embed_W)

# 単語ID
idx = 2

# 順伝播計算
emb.forward(idx)

# 逆伝播計算
dout = np.arange(D)
print("dout=", dout)
print()
emb.backward(dout)
print("dW=", emb.grads[0])
print()

embed_W= [[-0.07423256 -1.44963934 -0.52424659]
 [-0.78650298 -0.36239714  0.22783209]
 [-1.31534108  0.62346674  1.38215743]
 [-1.28681662 -0.96249888 -0.67505484]
 [-0.11172007 -1.10565705  1.82131453]
 [-0.37675701 -0.238562   -0.34137412]
 [-0.34971342 -0.74088063 -0.47488522]
 [-0.03102835 -1.07320138 -0.17333452]
 [ 0.75328459  0.87431296 -1.67433695]
 [-1.39156084  0.01867831 -0.07056924]]

dout= [0 1 2]

dW= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

