# ミニバッチ学習の実装

In [1]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import math

# Load the MNIST dataset
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(X_train, y_train),(X_test, y_test) = mnist.load_data()

from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()

train = X_train/255
test = X_test/255
train = train.reshape(-1, 28*28)
test = test.reshape(-1, 28*28)
train_labels = lb.fit_transform(y_train)
test_labels = lb.fit_transform(y_test)

/Users/yamaokadaichi/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## ミニバッチ学習
* ミニバッチ学習は、一般的には非復元抽出によって行われることが多いが、必ずこうしなければならないというわけではなく、分析者がデータセットの与え方を工夫することもできる。ただし、工夫しても計算が上手くいくとは限らない。
* 工夫のしどころ。
    * 一般的には、エポックのたびにシャッフルするが、シャッフルするタイミングを任意に変えてみる  
    * 与えるミニバッチ の順番を意図的に操作してみる   
        * 例、出現頻度の少ないラベルのデータを先に学習させる
    * 抽出されるラベルの割合が一定になるように抽出してみる
    * 復元抽出にしてみる

In [2]:
def trainer(network, x, y):
    """
    学習用の関数
    このnotebookでは、ミニバッチ学習を学ぶことが目的であるため、この関数の中身は空のままにしておく
    実際には、何らかの学習させるための処理を記述する
    """
    pass
    return 

### ミニバッチ学習のループ(復元抽出)

In [3]:
train_size = train_labels.shape[0]
batch_size = 32
max_iter = 10 #ループの回数
network = None #ダミー

for i in range(max_iter):
    print("i=%s"%i)
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = train[batch_mask]
    y_batch = train_labels[batch_mask]

    trainer(network, x_batch, y_batch)

i=0
i=1
i=2
i=3
i=4
i=5
i=6
i=7
i=8
i=9


### 復元抽出部分を理解するためのコード

In [4]:
batch_mask = np.random.choice(train_size, batch_size)
print("batch_mask=", batch_mask)
print()

x_batch = train[batch_mask]
print("x_batch=", x_batch)
print("x_batch.shape=", x_batch.shape)
print()
y_batch = train_labels[batch_mask]
print("y_batch=", y_batch)
print("y_batch.shape=", y_batch.shape)
print()

batch_mask= [38586 16917  6196 45260 34934 49417 48622 31137  1455 14549 13769 41256
 55277 55771 52206 44655 29912 23245 10255 20023 20658 24668 48790  9595
 59828 34308 39281 12674 15365 43732 30033 46315]

x_batch= [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
x_batch.shape= (32, 784)

y_batch= [[0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 

In [5]:
# 復元抽出部分(何回か実行してみてください)
np.random.choice(10,3)

array([1, 8, 8])

### ミニバッチ学習のループ(非復元抽出)

### [演習]
* 以下の非復元抽出によるミニバッチ学習を完成させましょう。
* 通常の計算では、非復元抽出で行うことが多いです。

In [6]:
# ヒント
index = np.arange(10)
print("index=%s"%index)
np.random.shuffle(index)
print("index=%s"%index)
print()
print(np.random.permutation(10))
print()

for i in range(4):
    print(index[3*i:3*(i+1)])

index=[0 1 2 3 4 5 6 7 8 9]
index=[4 9 6 7 8 1 2 3 5 0]

[2 9 3 0 1 4 5 8 7 6]

[4 9 6]
[7 8 1]
[2 3 5]
[0]


In [9]:
train_size = train_labels.shape[0]
batch_size = 32
epochs = 10
network = None #ダミー
minibatch_num = 10 # ミニバッチの個数
    
for epoch in range(epochs):
    print("epoch=%s"%epoch)
    
    # indexを定義し、シャッフルする
    index = 1
    np.random.shuffle()
    
    for mn in range():
        """
        非復元抽出によるループ
        """
        batch_mask = index[:]       
        x_batch = train[batch_mask]
        y_batch = train_labels[batch_mask]

        trainer(network, x_batch, y_batch)

epoch=0


TypeError: shuffle() takes exactly one argument (0 given)